type MetaData = {
  title: string,
  description: string,
  url: string,
  locale: string,
  tags?: string[],
  appleAppId?: string,
  metaTitle?: string,
  metaSiteName?: string,
  metaDescription?: string,
  metaUrl?: string,
  metaImage: string,
  metaImageType: string,
  metaImageSize: Size,
  appleAppId?: string,
}
